### ISSUE TITLE
Flutter chat not working

### ISSUE THREAD

**Issue by thekeels** [Apress/practical-flutter#3]
I am using flutter v1.9.1+hotfix.5. Running the flutter chat application results in crashes on both iOS and Android. See the corresponding issues on the flutter_socket_io project:

https://github.com/WinkMeter/flutter_socket_io/issues/17
https://github.com/WinkMeter/flutter_socket_io/issues/18

**Comment by fzammetti** [comment]
After updates for AndroidX compatibility and newer Flutter SDK, as well as dependencies, everything is working as expected for me now.

**Comment by mkrishnappa** [comment]
@fzammetti is it working on iOS as well?

**Comment by fzammetti** [comment]
I'm honestly not sure because I don't currently have the ability to test it on iOS. I know that it did work at the time of publication, and I'm not aware of anything that would make it not work now given the updates, but I can't confirm it.
