### ISSUE TITLE
Stuck on white screen 

### ISSUE THREAD

**Issue by richardfogaca** [Apress/practical-flutter#9]
I was constantly stuck on a white screen when trying to run the app, turns out the main method was missing the following line:
`WidgetsFlutterBinding.ensureInitialized();`

The error was due to mixing await and runApp() inside main().

Similar problem on Stackoverflow that fixed it for me:
[(https://stackoverflow.com/questions/57689492/flutter-unhandled-exception-servicesbinding-defaultbinarymessenger-was-accesse](url)

**Comment by Selecao** [comment]
I'm looking at _practical-flutter/ch_05+06/flutter_book/lib/main.dart_
 and at line 14 i see:
`WidgetsFlutterBinding.ensureInitialized();`
